backend = "xrender";
use-damage = false;


# --- Corners ---
corner-radius = 12;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

# Transparency:
inactive-opacity = 0.9;
active-opacity = 1.0;
frame-opacity = 0.8;
