
[color]
background = #262626
foreground = #FFFFFF
foreground-alt = #FFFFFF
shade1 = #005f87
shade5 = #44444
shade7 = #585858
#shade4 = #1E88E5
#shade5 = #2196F3
#shade6 = #42A5F5
#shade7 = #64B5F6
#shade8 = #90CAF9
